# docker-compose.yml

services:
  database:
    build: ./database
    container_name: timely-database
    environment:
      POSTGRES_DB: timely_db
      POSTGRES_USER: timely_user
      POSTGRES_PASSWORD: timely_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dataset:/shared/dataset:ro  # Dataset shared as read-only
      - initialization_flags:/shared/flags  # Shared flag storage
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timely_user -d timely_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: timely-backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ml_data:/app/data
      - ./dataset:/shared/dataset:ro  # Dataset shared as read-only
      - initialization_flags:/shared/flags  # Shared flag storage
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 8g 
        reservations:
          memory: 2g 

  frontend:
    build: ./frontend
    container_name: timely-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://localhost:5000/api
      - NODE_ENV=development
      - EVALUATION_SAMPLE_SIZE=100

volumes:
  postgres_data:
  ml_data:
  initialization_flags:  # New shared volume for initialization flags