# docker-compose.yml
version: '3.8'

services:
  database:
    build: ./database
    container_name: timely-database
    environment:
      POSTGRES_DB: timely_db
      POSTGRES_USER: timely_user
      POSTGRES_PASSWORD: timely_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timely_user -d timely_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: timely-backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ml_data:/app/data
      - ./data:/app/data/source:ro
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: timely-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:5000/api

volumes:
  postgres_data:
  ml_data: