# docker-compose.yml - UPDATED for new architecture

services:
  db:
    container_name: timely-db
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  init-db:
    container_name: timely-init-db
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./ml-service/training-data:/training-data
      - ./backend:/usr/src/app/backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: timely-backend
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ML_SERVICE_URL=http://ml-service:8000
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      init-db:
        condition: service_completed_successfully
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend:/app # Development mode
      - /app/node_modules 
    command: npm run dev 
    restart: unless-stopped

  ml-service:
    container_name: timely-ml-service
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - USE_DATABASE=true  # Direct database access
    ports:
      - "8000:8000"
    volumes:
      - ./ml-service/models:/app/models
      - ./ml-service/training-data:/app/training-data
    depends_on:
      db:
        condition: service_healthy
      init-db:
        condition: service_completed_successfully
    restart: unless-stopped

  frontend:
    container_name: timely-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_ML_API_URL: ${VITE_ML_API_URL}
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_ML_API_URL=${VITE_ML_API_URL}
    ports:
      - "3000:3000" 
    depends_on:
      - backend
    volumes:
      - ./frontend:/app # Development mode
      - /app/node_modules
    command: npm run dev 
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    name: timely-network