// frontend/src/pages/Profile.tsx
// UPDATED: Added AutoGenerateBasket component as banner variant
// PHASE 1: AutoGenerateBasket Integration Fix

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useForm } from 'react-hook-form';
import { useMutation, useQueryClient } from 'react-query';
import { useNavigate } from 'react-router-dom';
import {
  User, Mail, Phone, MapPin, Settings,
  Edit3, Save, X, CheckCircle, Shield
} from 'lucide-react';
import { useAuthStore } from '@/stores/auth.store';
import LoadingSpinner from '@/components/common/LoadingSpinner';
import { PageHeader } from '@/components/common/PageHeader';
import { Button } from '@/components/common/Button';
import { ResponsiveGrid } from '@/components/layout/ResponsiveGrid';
// ✅ ADDED: Import AutoGenerateBasket component
import AutoGenerateBasket from '@/components/predictions/AutoGeneratedBasket';
import toast from 'react-hot-toast';

interface ProfileFormData {
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
}

const Profile: React.FC = () => {
  const navigate = useNavigate();
  const { user, updateProfile } = useAuthStore();
  const queryClient = useQueryClient();
  const [isEditing, setIsEditing] = useState(false);

  const {
    register: registerProfile,
    handleSubmit: handleSubmitProfile,
    formState: { errors: profileErrors },
    reset: resetProfile
  } = useForm<ProfileFormData>({
    defaultValues: {
      firstName: user?.firstName || '',
      lastName: user?.lastName || '',
      email: user?.email || '',
      phone: '123-456'
    }
  });

  const updateProfileMutation = useMutation(updateProfile, {
    onSuccess: () => {
      setIsEditing(false);
      queryClient.invalidateQueries(['user-profile']);
      toast.success('Profile updated successfully! 🎉');
    },
    onError: (error: any) => {
      const errorMessage = error.response?.data?.message || 'Failed to update profile';
      toast.error(errorMessage);
    }
  });

  // ✅ ADDED: Handle navigation for AutoGenerateBasket component
  const handleNavigate = (path: string) => {
    navigate(path);
  };

  const onSubmitProfile = (data: ProfileFormData) => {
    updateProfileMutation.mutate(data);
  };

  const handleCancelEdit = () => {
    setIsEditing(false);
    resetProfile({
      firstName: user?.firstName || '',
      lastName: user?.lastName || '',
      email: user?.email || '',
      phone: '123-456'
    });
  };

  if (!user) {
    navigate('/login');
    return null;
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        
        <PageHeader
          title="My Profile"
          description="Manage your account information and preferences"
          icon={User}
        />

        <div className="space-y-8">
          
          {/* ✅ ADDED: AutoGenerateBasket Banner Component */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
          >
            <AutoGenerateBasket 
              variant="banner"
              onNavigate={handleNavigate}
              className="w-full"
            />
          </motion.div>

          {/* Profile Information Card */}
          <div className="bg-white rounded-lg shadow-sm">
            <div className="p-6 border-b border-gray-200">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <div className="w-16 h-16 bg-gradient-to-br from-indigo-500 to-purple-500 rounded-full flex items-center justify-center">
                    <span className="text-white font-bold text-xl">
                      {user.firstName?.charAt(0)}{user.lastName?.charAt(0)}
                    </span>
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900">
                      {user.firstName} {user.lastName}
                    </h3>
                    <p className="text-gray-600">{user.email}</p>
                    {user.role === 'admin' && (
                      <span className="inline-flex items-center gap-1 px-2 py-1 bg-indigo-100/30 text-indigo-800 text-xs font-medium rounded-full mt-1">
                        <Shield size={12} />
                        Administrator
                      </span>
                    )}
                  </div>
                </div>
                
                {!isEditing && (
                  <Button
                    onClick={() => setIsEditing(true)}
                    variant="primary"
                    icon={Edit3}
                  >
                    Edit Profile
                  </Button>
                )}
              </div>
            </div>

            <form onSubmit={handleSubmitProfile(onSubmitProfile)} className="p-6">
              <ResponsiveGrid cols={{ sm: 1, md: 2 }} gap={6}>
                
                {/* First Name */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    First Name
                  </label>
                  {isEditing ? (
                    <input
                      type="text"
                      {...registerProfile('firstName', { required: 'First name is required' })}
                      className="w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
                    />
                  ) : (
                    <div className="flex items-center gap-3 p-3 bg-gray-50 rounded-md">
                      <User size={16} className="text-gray-500" />
                      <span className="text-gray-900">{user.firstName}</span>
                    </div>
                  )}
                  {profileErrors.firstName && (
                    <p className="text-red-500 text-sm mt-1">{profileErrors.firstName.message}</p>
                  )}
                </div>

                {/* Last Name */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Last Name
                  </label>
                  {isEditing ? (
                    <input
                      type="text"
                      {...registerProfile('lastName', { required: 'Last name is required' })}
                      className="w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
                    />
                  ) : (
                    <div className="flex items-center gap-3 p-3 bg-gray-50 rounded-md">
                      <User size={16} className="text-gray-500" />
                      <span className="text-gray-900">{user.lastName}</span>
                    </div>
                  )}
                  {profileErrors.lastName && (
                    <p className="text-red-500 text-sm mt-1">{profileErrors.lastName.message}</p>
                  )}
                </div>

                {/* Email */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Email Address
                  </label>
                  <div className="flex items-center gap-3 p-3 bg-gray-50 rounded-md">
                    <Mail size={16} className="text-gray-500" />
                    <span className="text-gray-900">{user.email}</span>
                  </div>
                  <p className="text-xs text-gray-500 mt-1">
                    Email cannot be changed in demo mode
                  </p>
                </div>

                {/* Phone */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Phone Number
                  </label>
                  {isEditing ? (
                    <input
                      type="tel"
                      {...registerProfile('phone')}
                      placeholder="(555) 123-4567"
                      className="w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
                    />
                  ) : (
                    <div className="flex items-center gap-3 p-3 bg-gray-50 rounded-md">
                      <Phone size={16} className="text-gray-500" />
                      <span className="text-gray-900">{'Not provided'}</span>
                    </div>
                  )}
                </div>

              </ResponsiveGrid>

              {/* Action Buttons */}
              {isEditing && (
                <div className="flex items-center justify-end gap-3 mt-6 pt-6 border-t border-gray-200">
                  <Button
                    type="button"
                    onClick={handleCancelEdit}
                    variant="outline"
                    icon={X}
                  >
                    Cancel
                  </Button>
                  <Button
                    type="submit"
                    variant="primary"
                    icon={Save}
                    loading={updateProfileMutation.isLoading}
                  >
                    Save Changes
                  </Button>
                </div>
              )}
            </form>
          </div>

          {/* Account Information */}
          <div className="bg-white rounded-lg shadow-sm p-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Account Information</h3>
            
            <ResponsiveGrid cols={{ sm: 1, md: 2 }} gap={6}>
              <div>
                <p className="text-sm font-medium text-gray-700">Account Type</p>
                <div className="flex items-center gap-2 mt-1">
                  {user.role === 'admin' ? (
                    <>
                      <Shield size={16} className="text-indigo-600" />
                      <span className="text-indigo-600 font-medium">Administrator</span>
                    </>
                  ) : (
                    <>
                      <User size={16} className="text-gray-600" />
                      <span className="text-gray-900">Standard User</span>
                    </>
                  )}
                </div>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-700">Member Since</p>
                <p className="text-gray-900 mt-1">
                  {user.createdAt 
                    ? new Date(user.createdAt).toLocaleDateString('en-US', {
                        year: 'numeric',
                        month: 'long',
                        day: 'numeric'
                      })
                    : 'Unknown'
                  }
                </p>
              </div>
            </ResponsiveGrid>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Profile;